name: PR Title Updater

on:
  pull_request:
    types: [opened, edited]

jobs:
  update-pr-title:
    runs-on: ubuntu-latest
    steps:
      - name: Update PR Title
        uses: actions/github-script@v7
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
          script: |
            const pr = context.payload.pull_request;
            const branchName = pr.head.ref;
            const prTitle = `[${branchName}] ${pr.title}`;

            if (!pr.title.startsWith(`[${branchName}]`)) {
              github.rest.pulls.update({
                owner: context.repo.owner,
                repo: context.repo.repo,
                pull_number: pr.number,
                title: prTitle
              });
            }
